# Generated by Django 4.2.7 on 2023-12-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.person')),
                ('zip_code', models.PositiveIntegerField()),
            ],
            bases=('digikala.person',),
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.product')),
                ('material', models.CharField(choices=[('linen', 'Linen'), ('woolen', 'Woolen'), ('cotton', 'Cotton'), ('silk', 'Silk')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('baby', 'Baby')], max_length=10)),
                ('style', models.CharField(choices=[('slash', 'Slash'), ('normal', 'Normal'), ('classic', 'Classic')], max_length=10)),
                ('size', models.CharField(choices=[('s', 'S'), ('l', 'L'), ('xl', 'XL'), ('m', 'M')], max_length=2)),
                ('color', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=100)),
                ('heigh', models.CharField(max_length=100)),
            ],
            bases=('digikala.product',),
        ),
        migrations.CreateModel(
            name='Electronicdevice',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.product')),
                ('model', models.CharField(max_length=150)),
                ('use_for', models.CharField(choices=[('work', 'Work'), ('student', 'Student'), ('game', 'Game'), ('office', 'Office')], max_length=10)),
                ('storage_by_M', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
            ],
            bases=('digikala.product',),
        ),
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.product')),
                ('place', models.CharField(choices=[('kitchen', 'Kitchen'), ('livingroom', 'livingroom')], max_length=20)),
            ],
            bases=('digikala.product',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.person')),
                ('products_varity', models.CharField(choices=[('home Appliances', 'Home Appliances'), ('electronic device', 'Electronic device'), ('clothing', 'Clothing')], max_length=25)),
                ('score', models.PositiveIntegerField()),
            ],
            bases=('digikala.person',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem', to='digikala.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.product'),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('homeappliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.homeappliance')),
                ('material_body', models.CharField(choices=[('wood', 'Wood'), ('steal', 'Steal')], max_length=10)),
                ('Capacity', models.DecimalField(decimal_places=1, max_digits=15)),
            ],
            bases=('digikala.homeappliance',),
        ),
        migrations.CreateModel(
            name='KitchenAppliance',
            fields=[
                ('homeappliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.homeappliance')),
                ('work_with', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=20)),
            ],
            bases=('digikala.homeappliance',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('electronicdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.electronicdevice')),
                ('ram', models.PositiveIntegerField()),
                ('cpu_model', models.CharField(max_length=150)),
                ('number_core', models.PositiveIntegerField()),
                ('resolution', models.CharField(choices=[('1920×1080', '1920×1080'), ('3840×2160', '3840×2160'), ('1280×720', '1280×720')], max_length=11)),
                ('screan_size', models.FloatField()),
                ('webcam', models.BooleanField(default=False)),
            ],
            bases=('digikala.electronicdevice',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('electronicdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.electronicdevice')),
                ('screen_size', models.FloatField()),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.PositiveIntegerField()),
                ('camera', models.PositiveIntegerField()),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'Ios')], max_length=10)),
                ('sim_number', models.PositiveIntegerField()),
            ],
            bases=('digikala.electronicdevice',),
        ),
        migrations.CreateModel(
            name='pants',
            fields=[
                ('clothing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.clothing')),
                ('crotch', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=10)),
            ],
            bases=('digikala.clothing',),
        ),
        migrations.CreateModel(
            name='T_shirt',
            fields=[
                ('clothing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.clothing')),
                ('Sleeve', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=10)),
            ],
            bases=('digikala.clothing',),
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('homeappliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.homeappliance')),
                ('quality', models.CharField(choices=[('4K', '4K'), ('FULLHD', 'FULLHD'), ('HD', 'HD')], max_length=6)),
                ('technology', models.CharField(default='LED', max_length=50)),
            ],
            bases=('digikala.homeappliance',),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.client'),
        ),
        migrations.AddField(
            model_name='electronicdevice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikala.seller'),
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('kitchenappliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.kitchenappliance')),
                ('gas_type', models.CharField(choices=[('stove', 'Stove'), ('sheet', 'Sheet')], max_length=5)),
                ('quality', models.CharField(choices=[('glass', 'Glass'), ('steal', 'Steal')], max_length=5)),
                ('flame_number', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('digikala.kitchenappliance',),
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('kitchenappliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digikala.kitchenappliance')),
                ('power_usage', models.CharField(choices=[('a+', 'A+'), ('a++', 'A++'), ('b', 'B'), ('a', 'A')], max_length=3)),
                ('capacity_litre', models.PositiveIntegerField()),
            ],
            bases=('digikala.kitchenappliance',),
        ),
    ]
